let athletes = [
    { name: "Usain Bolt", dec: "Usain Bolt is a retired Jamaican sprinter, widely regarded to be the greatest sprinter of all time. He is the world record holder in the 100 meters, 200 meters, and 4 × 100 meters relay.", img: "asset/img/atheletes/300890817-155557270479663-493078166280071531-n-800x448.jpg" },
    { name: "Simone Biles", dec: "Biles stormed the gymnastics scene when she won five medals at the 2016 Olympic Games in Rio: gold in the team event, the individual all-around competition, the vault and the floor exercise. She also took home the bronze in the balance beam final. The athlete set an American record for most gold medals won at a single Games.", img: "asset/img/atheletes/Simone-Biles-Then-Olympic-Athletes-Where-Are-They-Now (1).jpg" },
    { name: "Lindsey Vonn", dec: "Skier Vonn, who made her Olympic debut in 2002 at age 17, was the first American woman to nab a gold medal in the downhill event at the 2010 Winter Olympics. (She also took home a bronze in 2010's Super-G race.)", img: "asset/img/atheletes/Lindsey-Vonn-Then-97140588.jpg" },
    { name: "Michael Jordan ", dec: "Michael Jordan is an American businessman and former professional basketball player. He played fifteen seasons in the National Basketball Association (NBA), winning six NBA championships with the Chicago Bulls.", img: "asset/img/atheletes/michael-jordan.jpg" },
    { name: "Muhammad Ali", dec: "Muhammad Ali was an American professional boxer and activist. Nicknamed “The Greatest”, he is widely considered one of the most important and renowned sports figures of the 20th century", img: "asset/img/atheletes/muhammad-ali-435-1-3a9eced7720841e9ae8f2b7448b14f7b.jpg" },
    { name: "Wayne Gretzky", dec: "Wayne Gretzky is a Canadian former professional ice hockey player and former head coach. He played 20 seasons in the National Hockey League (NHL) for four teams from 1979 to 1999.", img: "asset/img/atheletes/edmonton-wayne-gretzky-031516-getty-ftrjpg_btjzlzxrrpec1covu0vtbck2u.jpg" },
    { name: "Babe Ruth", dec: "Babe Ruth was an American professional baseball player whose career in Major League Baseball (MLB) spanned 22 seasons, from 1914 through 1935.", img: "asset/img/atheletes/image-4-5.webp" },
    { name: "Roger Federer", dec: "Roger Federer is a Swiss professional tennis player. He was rated world No. 1 by the Association of Tennis Professionals for 310 weeks, including a record 237 consecutive weeks, and has spent as the year-end No. 1 five times.He has won 103 ATP singles titles, the second-most of all time after Jimmy Connors, including 20 Grand Slam titles, a record eighth men’s singles Wimbledon titles, and a record six year-end championships.", img: "asset/img/atheletes/309059710-1144542213122630-558252689369347420-n-768x513.jpg" },
    { name: "Barbara Reed", dec: "Indoors, the Swedish 24-year-old added a centimetre to his previous outright best, clearing 6.22m in Clermont-Ferrand. During the outdoor season, he secured his second consecutive world title in Budapest and then won his third Wanda Diamond League trophy with a clearance of 6.23m on his first attempt to better his world record by another centimetre.", img: "asset/img/atheletes/f.txt.jpg" }
]

let games = [
    { title: "Acrobatic Gymnastics", dec: "Acrobatic gymnastics is a competitive discipline of gymnastics where partnerships of gymnasts work together and perform figures consisting of acrobatic", pic: "asset/img/Games/Acrobatic Gymnastics.png" },
    { title: "Alpine Skiing", dec: "Alpine skiing is the sport of sliding down snow-covered hills on skis with fixed-heel bindings. It is also commonly known as downhill skiing, although that also incorporates different styles.", pic: "asset/img/Games/Alpine Skiing.svg" },
    { title: "Archery", dec: "Archery is a bow and arrow sport that uses a bow and arrow to shoot at a target. The target often consists of ten concentric circles, and points are awarded based on which circle the bow lands in.", pic: "asset/img/Games/Archery.svg" },
    { title: "Artistic Swimming", dec: "Synchronized swimming (in British English, synchronised swimming) or artistic swimming is a sport where swimmers perform a synchronized choreographed routine, accompanied by music.", pic: "asset/img/Games/Artistic Swimming.svg" },
    { title: "Athletics", dec: "Athletics is a group of sporting events that involves competitive running, jumping, throwing, and walking.", pic: "asset/img/Games/Athletics.svg" },
    { title: "Badminton", dec: "Badminton is a sport in which light rackets are used to volley an object—called a shuttlecock, shuttle, birdie, or bird—back and forth over a high net.", pic: "asset/img/Games/Badminton.svg" },
    { title: "Beach Volleyball", dec: "Beach volleyball is a team sport played by two teams of two players each on a sand court divided by a net.", pic: "asset/img/Games/Beach Volleyball.svg" },
    { title: "Boxing", dec: "Boxing is a sport that involves strategically punching an opponent while defending yourself from their return punches.", pic: "asset/img/Games/Boxing.svg" },
    { title: "Breaking", dec: "Acrobatic movements, stylised footwork, and the key role played by the DJ and the MC (master of ceremonies) during battles.", pic: "asset/img/Games/Breaking.svg" },
    { title: "Fencing", dec: "Fencing is a sport in which two competitors fight each other using very thin swords.", pic: "asset/img/Games/Fencing.svg" },
    { title: "Figure Skating", dec: "Figure skating, sport in which ice skaters, singly or in pairs, perform freestyle movements of jumps, spins, lifts, and footwork in a graceful manner.", pic: "asset/img/Games/Figure Skating.svg" },
    { title: "Football", dec: "Football or soccer, is a game involving two teams of 11 players who try to maneuver the ball into the other team's goal without using their hands or arms.", pic: "asset/img/Games/Football.svg" },
    { title: "Freestyle Skiing", dec: "Freestyle skiing, winter sport that combines skiing and acrobatics", pic: "asset/img/Games/Freestyle Skiing.svg" },
    { title: "Hockey", dec: "Hockey is a type of sport in which players try to get points by hitting an object into the other team's goal with a stick.", pic: "asset/img/Games/Hockey.svg" },
    { title: "Judo", dec: "Judo, system of unarmed combat, now primarily a sport. The objective is to cleanly throw, to pin.", pic: "asset/img/Games/Judo.svg" },
    { title: "Karate", dec: "Karate is a Japanese martial art whose physical aspects seek the development of defensive and counterattacking body movements.", pic: "asset/img/Games/Karate.svg" },
    { title: "Rhythmic Gymnastics", dec: "Rhythmic Gymnastics is a discipline combining grace, coordination, agility and artistry.", pic: "asset/img/Games/Rhythmic Gymnastics.svg" },
    { title: "Roller Skating", dec: "Roller skating is the act of travelling on surfaces with roller skates.", pic: "asset/img/Games/Roller speed Skating.svg" },
    { title: "Rowing", dec: "Rowing, often called crew in the United States, is the sport of racing boats using oars.", pic: "asset/img/Games/Rowing.svg" },
    { title: "Sailing", dec: "The sport of sailing is racing other boats around a track or course which is marked with floating buoys or other fixed marks.", pic: "asset/img/Games/Sailing.svg" },
    { title: "Shooting", dec: "Rifle, pistol and shotgun. Rifle and pistol events take place on shooting ranges, where athletes aim at targets at distances of 10m, 25m and 50m.", pic: "asset/img/Games/Shooting.svg" },
    { title: "Jumping", dec: "Riders and horses are timed as they jump over obstacles, with time penalties imposed for each obstacle toppled.", pic: "asset/img/Games/Ski Jumping.svg" },
];

let gallery = [
    {img:"asset/img/453899741_18447603832065324_927665523409569235_n.jpg", alt:""},
    {img:"asset/img/454035144_18447603841065324_7822349421405304292_n.jpg", alt:""},
    {img:"asset/img/454209072_18447603865065324_5329159756508384821_n.jpg", alt:""},
    {img:"asset/img/alpine skiing.jpg", alt:""},
    {img:"asset/img/archery.jpg", alt:""},
    {img:"asset/img/artistic swimming.jpg", alt:""},
    {img:"asset/img/athletics 1.jpg", alt:""},
    {img:"asset/img/athletics 2.jpg", alt:""},
    {img:"asset/img/athletics 3.jpg", alt:""},
    {img:"asset/img/badminton.jpg", alt:""},
    {img:"asset/img/beach volly ball.jpg", alt:""},
    {img:"asset/img/boxing.jpg", alt:""},
    {img:"asset/img/download.jpeg", alt:""},
    {img:"asset/img/fencing.jpg", alt:""},
    {img:"asset/img/figure skating.jpg", alt:""},
    {img:"asset/img/football.jpg", alt:""},
    {img:"asset/img/freestyle skiing.jpg", alt:""},
    {img:"asset/img/hockey.jpg", alt:""},
    {img:"asset/img/judo.jpg", alt:""},
    {img:"asset/img/karate.jpg", alt:""},
    {img:"asset/img/OIP (1).jpeg", alt:""},
    {img:"asset/img/R.jpeg", alt:""},
    {img:"asset/img/rollar skating.jpg", alt:""},
    {img:"asset/img/Rowing.jpg", alt:""},
    {img:"asset/img/Sailing.jpg", alt:""}
]
